frase = 'Curso em Video Python'
print(frase.find('rso'))
print(frase.count('i'))
print(frase.upper().count('O'))
print(frase.replace('Python', 'Santos'))
print('Curso' in frase)
print(frase.lower().find('video'))
print(frase.split())
dividido = frase.split()
print(dividido[0])
print(dividido[3][3])